### ISSUE TITLE
Bug with .dat file after update

### ISSUE THREAD

**Issue by Merovinglen** [DavidMoore/ipfilter#22]
Hello :),

After running the ipfilter.dat updater, the ipfilter.dat file is not the same if i compare the two in my appdata folder and the one in appdata\davidmoore folder.

Mine show a date : 2015-06-13 and the new one is dated of 2016-04-10.

Why? Is there something I'm doing wrong?

![my appdata ipfilter file](https://cloud.githubusercontent.com/assets/18689208/14836637/8e6e3050-0bdf-11e6-98e6-15b9396098e6.jpg)
![david moore appdata ipfilter file](https://cloud.githubusercontent.com/assets/18689208/14836638/8e6ef67a-0bdf-11e6-9885-7ea2964ccfe8.jpg)

**Comment by DavidMoore** [comment]
Hi. You should look at the Modified Date instead of the Date Created; the ipfilter.dat in your uTorrent folder is created 2015-06-13 but it's actually been updated on 2016-04-26.

When you updated the filter, did it say what the timestamp of the filter was after it finished updating? And was there information in the log about updating uTorrent properly?

**Comment by Merovinglen** [comment]
its ok.  i was not looking at the rjght place.  sorry

**Comment by DavidMoore** [comment]
No problems!
