### ISSUE TITLE
Try icon please :)

### ISSUE THREAD

**Issue by ukaszek2nd** [DavidMoore/ipfilter#23]
Try icon please :)

**Comment by travd93** [comment]
Are you asking for a Tray Icon when minimised? Because if you are I would highly agree.
I have a W7 box I leave on 24/7 in use with Sonar. Would be very neat to have just an icon in the tray instead of Task-bar. David I've been using your app for 3+ years, even when it was just a batch file.
From a long time user I would really appreciate such a feature.

**Comment by ukaszek2nd** [comment]
Yes, yes I think about tray icon when app is minimised... I have opened the program all the time and just a task bar isn't good idea for me... It's little confusing for use... Sorry for my language 😅

**Comment by DavidMoore** [comment]
I agree on both accounts, a proper icon + system tray. I found that the task scheduling can't be done if you're not an admin, so system tray makes more sense.

**Comment by ukaszek2nd** [comment]
And my dear David??? :)  Have u tried make try icon??? Or too little time :P Just kidding :)

**Comment by JonnyRedHed** [comment]
A unique icon for ipfilter would be a good to have.  One that works small and large, and on program bar and system tray.

**Comment by DavidMoore** [comment]
Hi. I have a prototype of the system tray, and will have to use a simple icon for now until I can make a nicer one later. I've been playing too much Overwatch, but should be able to update this weekend :)

**Comment by DavidMoore** [comment]
The new version has a nice ugly icon now. At some point maybe we can make it prettier but it's better than nothing I guess :D
