### ISSUE TITLE
Command-line parameter to update and exit?

### ISSUE THREAD

**Issue by rosslevis** [DavidMoore/ipfilter#31]
Just wondering if this is already supported, if not, it is a suggestion.  One can then set the Windows Task Scheduler to update the IP list on a daily regular basis without having the app open permanently.

**Comment by DavidMoore** [comment]
Hi there. IPFilter actually does just this, scheduling a silent update using Windows Task Scheduler.

This has proven to be problematic due to security and permissions, so instead the next release will run in the background in the system tray.

If you want to manually set up a scheduled task or similar, you can run `ipfilter /silent` to get IPFilter to do an update then exit from the command line.

**Comment by DavidMoore** [comment]
Hi @rosslevis did the command line parameter work for you?
