### ISSUE TITLE
Errors in Win 10 creators version

### ISSUE THREAD

**Issue by ludespeedny** [DavidMoore/ipfilter#37]
I cannot run this on my machines that have the Creators Update. Possibly some Net Framework 4.7 issues? My other Win 10 machine runs it fine. (Was working on my Win 10 machine before the creators update)
Attached are the 2 event log errors it generates.

[logs.zip](https://github.com/DavidMoore/ipfilter/files/903378/logs.zip)

**Comment by BothGunzUP** [comment]
Application Error:
Faulting application name: IPFilter.exe, version: 2.2.2.0, time stamp: 0x5731b7df
Faulting module name: d3d9.dll, version: 10.0.15063.0, time stamp: 0x631de416
Exception code: 0xc0000005
Fault offset: 0x000000000000fd0c
Faulting process id: 0xfb4
Faulting application start time: 0x01d2b259f0a8fd38
Faulting application path: C:\Users\BothG\Desktop\IPFilter.exe
Faulting module path: C:\WINDOWS\SYSTEM32\d3d9.dll
Report Id: 02e6b00c-8958-4a53-a4b4-3b7e5245a6fa
Faulting package full name: 
Faulting package-relative application ID: 

.NET Runtime Error:
Application: IPFilter.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FFD281CFD0C

**Comment by DavidMoore** [comment]
Hi. Crash is coming from the DirectX 3D library maybe? Are there any other .NET apps you're seeing crashing in this manner?

I'll see if I can opt in to the update and see if I can reproduce at home.

**Comment by ludespeedny** [comment]
I think there was an error or something on the Win 10 side. It started working for me again yesterday. I think it may  have been an update that fixed the .net side of things.
